version: '3.8'
services:
  minesweeper:
    build: .
    image: minesweeper-java
    container_name: minesweeper_game
    # Share the host's display environment variable
    environment:
      - DISPLAY=${DISPLAY}
    # Mount the X11 socket to allow GUI communication
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    # Use host networking to simplify display connection (works best on Linux)
    network_mode: host
